FROM python:3.9.1


RUN apt-get install wget
RUN pip install pandas sqlalchemy pyarrow psycopg2

WORKDIR /app/data

COPY $PWD/src/data_upload.py data_upload.py

ENTRYPOINT [ "python", "data_upload.py" ]


